import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { MQTTProvider } from "../mqtt/mqtt-client";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="container mx-auto max-w-4xl p-4">
        <TRPCReactProvider>
          <MQTTProvider>{children}</MQTTProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
